"""Continental Legacy pipeline backed by the native terrain core."""

from __future__ import annotations

from collections.abc import Callable
import random

import numpy as np

from ...core.request import GenerationRequest
from ...core.seed_streams import SeedStreams
from ....map_data.constants import SNOW, SNOW_TRANS, WATER_IDS
from ....map_data.hexgrid import dilate, neighbor_count
from ...archetypes.continental import assemble_continental_state
from .native_terrain import generate_primary_terrain, resume_deferred_terrain
from .native_validators import validate
from .objects import finalize_accessibility
from .profile import load_profile
from .starts import place_starts


Progress = Callable[[str, str], None] | None


def generate(
    request: GenerationRequest,
    progress: Progress = None,
    *,
    mirror_mode: int = 0,
    profile: dict | None = None,
) -> tuple[object, list]:
    """Generate one Continental Legacy map with native-calibrated content.

    The native terrain core owns the terrain morphology and the global
    object/resource pass.  Only player-start objects/resources, settlers and
    SAV records stay deferred; the native global content is copied directly
    into the MAP/EDM six-channel state.
    """

    def stage(key: str, detail: str, fn):
        if progress:
            progress(key, detail)
        return fn()

    profile = profile if profile is not None else load_profile()
    custom_runtime = profile.get("_custom_runtime", {})
    is_custom = (
        isinstance(custom_runtime, dict)
        and bool(custom_runtime)
        and custom_runtime.get("execution_kind", "custom") != "preset"
    )
    if is_custom and custom_runtime.get("base_mode") not in (None, "legacy"):
        raise ValueError("Un profil Custom Legacy doit conserver Legacy comme moteur de base")
    custom_sections = (
        custom_runtime.get("sections")
        if isinstance(custom_runtime, dict)
        and isinstance(custom_runtime.get("sections"), dict)
        and custom_runtime.get("sections")
        else None
    )

    # A changed Custom object family must not be generated by the native
    # pass only to be erased later.  Tell that pass which families are owned
    # by the semantic Custom layer; unchanged families remain byte-for-byte
    # native and still use the native placement.
    disabled_native_object_families: tuple[str, ...] = ()
    if custom_sections is not None:
        from ...custom.objects import semantic_object_changes

        _, replace_trees, replace_stones, replace_decorations = semantic_object_changes(
            profile,
            custom_sections,
        )
        disabled_native_object_families = tuple(
            key
            for key, enabled in (
                ("trees", replace_trees),
                ("stones", replace_stones),
                ("decorations", replace_decorations),
            )
            if enabled
        )

    active_start_packages = (
        tuple(str(value) for value in custom_runtime.get("start_packages", ()))
        if is_custom and isinstance(custom_runtime.get("start_packages", ()), (list, tuple))
        else ()
    )
    priority_bonus_route = bool(active_start_packages)

    result = stage(
        "continental_legacy.native_terrain",
        "relief, surfaces, rivières et transitions natives",
        lambda: generate_primary_terrain(
            request.side,
            request.seed,
            mirror_mode,
            progress=lambda name: progress(f"continental_legacy.native.{name}", "") if progress else None,
            surface_rates=custom_sections,
            disabled_object_families=disabled_native_object_families,
            defer_non_archetype=priority_bonus_route,
            defer_global_content=priority_bonus_route,
        ),
    )
    mode_label = "Custom" if is_custom else "Legacy"
    mode_key = "custom" if is_custom else "legacy"
    generator_name = "continental_custom_legacy" if is_custom else "continental_legacy_native_content"
    engine_revision = (
        f"continental_custom_legacy-v1:{custom_runtime.get('configuration_digest', '')}"
        if is_custom else "continental_legacy_native-legacy-v1"
    )
    state = assemble_continental_state(
        request.side,
        result.height,
        result.terrain,
        metadata={
            "seed": int(request.seed),
            "players": int(request.players),
            "mode": mode_label,
            "mode_key": mode_key,
            "archetype": "Continental",
            "archetype_key": "continental",
            "profile": profile["profile_name"],
            "generator": generator_name,
            "engine_revision": engine_revision,
            "custom_base_mode": custom_runtime.get("base_mode") if is_custom else None,
            "custom_configuration_digest": custom_runtime.get("configuration_digest") if is_custom else None,
            "custom_start_packages": custom_runtime.get("start_packages", []) if is_custom else None,
            "generator_route": (
                "custom_preset"
                if isinstance(custom_runtime, dict)
                and custom_runtime.get("execution_kind") == "preset"
                else "custom"
                if is_custom
                else "native"
            ),
            "runtime_native_inputs": 0,
            "start_bonus_priority_route": priority_bonus_route,
            "active_start_packages": list(active_start_packages),
            "native_deferred_layers": (
                "starts_native", "settlers", "sav_writer"
            ),
            **result.metadata,
        },
    )
    if result.objects is None or result.resources is None:
        raise RuntimeError("Le cœur natif n'a pas renvoyé ses couches de contenu")
    state.objects[:] = result.objects
    state.resources[:] = result.resources

    custom_resources = None
    if custom_sections is not None and not priority_bonus_route:
        from ...custom.content import apply_custom_resource_sections

        custom_resources = apply_custom_resource_sections(
            state,
            custom_sections,
            np.random.default_rng(int(request.seed) ^ 0x43555354),
        )
        state.metadata["custom_resource_controls"] = custom_resources
        state.metadata["minerals"] = custom_resources["minerals"]
        state.metadata["fish"] = custom_resources["fish"]

    # The current export format still expects a PlayerInfo coordinate list.
    # Keep the old deterministic bridge isolated after terrain generation; it
    # cannot influence the native field and is explicitly marked provisional.
    start_occupied = stage(
        "continental_legacy.starts_bridge",
        "coordonnées provisoires pour le scaffold MAP/EDM",
        lambda: place_starts(
            state,
            request.players,
            SeedStreams(request.seed).rng("starts_bridge"),
            technical_clear=max(12, request.side // 52),
        ),
    )
    state.metadata.update(
        starts_status="provisional_bridge_not_native",
        starts_placed_early=True,
        start_placement_deferred=False,
    )

    custom_start_bonuses: dict[str, object] = {}
    custom_objects = None
    priority_object_results: dict[str, object] = {}
    bonus_content = None
    if priority_bonus_route:
        # The active Custom route is deliberately staged: start terrain is
        # painted into the archetype field, native non-archetype terrain is
        # resumed around it, then start resources/objects are written before
        # the global content pass.
        from ..upgraded.content import UpgradedContent
        from ..upgraded.profile_defaults import active_upgraded_profile

        bonus_profile = active_upgraded_profile()
        bonus_profile["_custom_runtime"] = custom_runtime
        bonus_content = UpgradedContent(bonus_profile)
        terrain_bonus_meta = bonus_content.begin_prioritized_terrain_bonuses(
            state,
            random.Random(SeedStreams(request.seed).value("legacy_custom_start_bonuses")),
        )
        custom_start_bonuses.update(
            {
                key: value
                for key, value in terrain_bonus_meta.items()
                if key != "protected_mask"
            }
        )
        priority_callback_state: dict[str, object] = {}

        def before_native_content(grid):
            # Resume works on the native temporary grid so its PRNG stream is
            # preserved.  Synchronize the fully resumed terrain into the
            # application state before placing the start object packages.
            state.height[:] = grid.height
            state.terrain[:] = grid.terrain
            state.objects[:] = grid.objects
            state.resources[:] = grid.resources

            if custom_sections is not None:
                from ...custom.content import apply_custom_resource_sections

                selected_resources = apply_custom_resource_sections(
                    state,
                    custom_sections,
                    np.random.default_rng(int(request.seed) ^ 0x43555354),
                    excluded_mask=terrain_bonus_meta["protected_mask"],
                )
                priority_callback_state["custom_resources"] = selected_resources
                state.metadata["custom_resource_controls"] = selected_resources
                state.metadata["minerals"] = selected_resources["minerals"]
                state.metadata["fish"] = selected_resources["fish"]

            bonus_content.apply_prioritized_start_resources(
                state,
                np.random.default_rng(int(request.seed) ^ 0x53544152),
            )

            start_forest = {}
            start_stones = {}
            if custom_sections is not None:
                from ...custom.objects import (
                    apply_custom_legacy_start_forest,
                    apply_custom_legacy_start_stones,
                )

                start_forest = apply_custom_legacy_start_forest(
                    state,
                    profile,
                    custom_sections,
                    np.random.default_rng(int(request.seed) ^ 0x53544652),
                )
                start_stones = apply_custom_legacy_start_stones(
                    state,
                    profile,
                    custom_sections,
                    np.random.default_rng(int(request.seed) ^ 0x53545354),
                )
            priority_object_results["start_forest"] = start_forest
            priority_object_results["start_building_stones"] = start_stones
            custom_start_bonuses["forest"] = start_forest
            custom_start_bonuses["building_stones"] = start_stones

            protected_objects = np.asarray(start_occupied, dtype=bool).copy()
            protected_objects |= state.objects != 0
            protected_objects |= np.asarray(
                terrain_bonus_meta["protected_mask"],
                dtype=bool,
            )
            bonus_object_cells = state.objects != 0
            for cell in state.metadata.get("legacy_start_building_stone_footprint_cells", ()):
                if isinstance(cell, (tuple, list)) and len(cell) == 2:
                    x, y = int(cell[0]), int(cell[1])
                    if 0 <= x < state.side and 0 <= y < state.side:
                        bonus_object_cells[y, x] = True
                        protected_objects[y, x] = True

            # Protect the actual bonus object footprints and their calibrated
            # distance halo.  The technical start mask and bonus terrain stay
            # exact; only written object cells receive the object clearance.
            bonus_object_clearance = dilate(bonus_object_cells, 2)
            priority_callback_state["start_bonus_object_clearance"] = (
                bonus_object_clearance
            )
            protected_objects |= bonus_object_clearance

            # Native content now sees the actual start writes and cannot place
            # an object on an already occupied/footprint cell.
            grid.height[:] = state.height
            grid.terrain[:] = state.terrain
            grid.objects[:] = state.objects
            grid.resources[:] = state.resources
            return {
                "protected_object_mask": protected_objects,
                "protected_resource_mask": np.asarray(
                    terrain_bonus_meta["protected_mask"],
                    dtype=bool,
                ),
            }

        resumed = resume_deferred_terrain(
            result,
            height=state.height,
            terrain=state.terrain,
            objects=state.objects,
            resources=state.resources,
            protected_mask=terrain_bonus_meta["protected_mask"],
            include_native_content=True,
            include_native_resources=custom_sections is None,
            preserve_existing_resources=True,
            object_hitbox_radius=2 if priority_bonus_route else None,
            before_native_content=before_native_content,
            progress=lambda name: progress(f"continental_legacy.native.{name}", "") if progress else None,
        )
        result = resumed
        state.height[:] = resumed.height
        state.terrain[:] = resumed.terrain
        state.objects[:] = resumed.objects
        state.resources[:] = resumed.resources
        state.metadata.update(resumed.metadata)
        custom_resources = priority_callback_state.get("custom_resources")
        if isinstance(custom_resources, dict):
            state.metadata["custom_resource_controls"] = custom_resources
            state.metadata["minerals"] = custom_resources["minerals"]
            state.metadata["fish"] = custom_resources["fish"]
        bonus_content.apply_prioritized_start_fish(
            state,
            np.random.default_rng(int(request.seed) ^ 0x53544649),
        )
        state.metadata["start_bonus_priority_order"] = (
            "terrain_before_global_terrain",
            "start_objects_before_global_objects",
        )

        if custom_sections is not None:
            from ...custom.objects import apply_custom_legacy_objects

            custom_objects = apply_custom_legacy_objects(
                state,
                profile,
                custom_sections,
                start_occupied,
                np.random.default_rng(int(request.seed) ^ 0x4F424A53),
                start_bonus_object_clearance=priority_callback_state.get(
                    "start_bonus_object_clearance"
                ),
            )
            custom_objects["start_forest"] = priority_object_results.get("start_forest", {})
            custom_objects["start_building_stones"] = priority_object_results.get("start_building_stones", {})
            if (
                custom_objects.get("replaced")
                or custom_objects["start_forest"].get("enabled")
                or custom_objects["start_building_stones"].get("enabled")
            ):
                state.metadata["custom_object_controls"] = custom_objects
    elif custom_sections is not None:
        from ...custom.objects import (
            apply_custom_legacy_objects,
            apply_custom_legacy_start_forest,
            apply_custom_legacy_start_stones,
        )

        start_forest = apply_custom_legacy_start_forest(
            state,
            profile,
            custom_sections,
            np.random.default_rng(int(request.seed) ^ 0x53544652),
        )
        start_stones = apply_custom_legacy_start_stones(
            state,
            profile,
            custom_sections,
            np.random.default_rng(int(request.seed) ^ 0x53545354),
        )
        custom_start_bonuses["forest"] = start_forest
        custom_start_bonuses["building_stones"] = start_stones

        custom_objects = apply_custom_legacy_objects(
            state,
            profile,
            custom_sections,
            start_occupied,
            np.random.default_rng(int(request.seed) ^ 0x4F424A53),
        )
        custom_objects["start_forest"] = start_forest
        custom_objects["start_building_stones"] = start_stones
        if (
            custom_objects.get("replaced")
            or start_forest.get("enabled")
            or start_stones.get("enabled")
        ):
            state.metadata["custom_object_controls"] = custom_objects

    if custom_start_bonuses:
        state.metadata["custom_start_bonuses"] = custom_start_bonuses
    if priority_bonus_route:
        state.metadata["pipeline"] = [
            "archetype.macro_layout",
            "legacy.native_terrain_archetype",
            "legacy.starts_bridge",
            "legacy.start_bonus_terrain",
            "legacy.native_terrain_non_archetype",
            "legacy.start_bonus_resources",
            "legacy.start_bonus_objects",
            "legacy.native_global_content",
            "legacy.custom_global_objects",
            "legacy.accessibility",
            "legacy.validate",
        ]

    water = np.isin(state.terrain, WATER_IDS)
    state.height[water] = 0
    state.accessibility[water] = 1
    snow = np.isin(state.terrain, (SNOW_TRANS, SNOW))
    state.accessibility[snow] = 1
    state.metadata["native_variant_field_checksum"] = int(result.variant.astype(np.uint64).sum())
    state.metadata["native_auxiliary_fields_deferred"] = False
    state.metadata["native_river_water_facing_cells"] = int(
        np.count_nonzero((state.terrain >= 0x60) & (state.terrain <= 0x63) & (neighbor_count(water) > 0))
    )
    native_content = result.metadata.get("native_content", {})
    if not isinstance(native_content, dict):
        native_content = {}
    for layer, detail in (
        ("minerals", "gisements de montagne"),
        ("fish", "poissons sur eaux hors rivières"),
        ("trees", "arbres et palmiers"),
        ("stones", "pierres de construction"),
        ("decorations", "objets statiques et décorations"),
    ):
        if custom_resources is not None and layer in {"minerals", "fish"}:
            detail = custom_resources[layer]
        custom_layer = (
            custom_objects.get(layer)
            if isinstance(custom_objects, dict)
            and layer in {"trees", "stones", "decorations"}
            and isinstance(custom_objects.get(layer), dict)
            and custom_objects.get(layer)
            else None
        )
        # Keep the established UI/progress contract while the actual native
        # work has already run in the shared native PRNG pass.
        state.metadata.update(stage(
            f"continental_legacy.{layer}",
            custom_layer if custom_layer is not None else detail,
            lambda layer=layer, custom_layer=custom_layer: (
                custom_layer if custom_layer is not None else native_content.get(layer, {})
            ),
        ))
    state.metadata.update(stage(
        "continental_legacy.accessibility",
        "accessibilité finale",
        lambda: finalize_accessibility(state),
    ))
    validations = stage(
        "continental_legacy.native_validate",
        "terrain, ressources et objets",
        lambda: validate(state, mode=mirror_mode),
    )
    state.metadata["native_content_provenance"] = {
        "minerals": "routines globales Legacy, sans ressources de départ",
        "fish": "boucle globale Legacy, sans ressources de départ",
        "objects": "appels statiques/rangés Legacy",
        "decorations": "objets statiques globaux Legacy, hors objets de départ SAV",
    }
    if is_custom:
        state.metadata["custom_profile_applied"] = bool(
            custom_sections is not None or active_start_packages
        )
        state.metadata["custom_profile_diagnostics"] = {
            "base_mode": custom_runtime.get("base_mode", "legacy"),
            "base_archetype": custom_runtime.get("base_archetype", "continental"),
            "configuration_digest": custom_runtime.get("configuration_digest"),
            "active_start_packages": list(custom_runtime.get("start_packages", [])),
            "profile_sections": sorted(
                key for key in profile
                if not str(key).startswith("_")
            ),
            "unapplied_sections": sorted(
                key for key in profile
                if not str(key).startswith("_")
                and key not in {"profile_name", "profile_kind", "side", "max_players", "supported_players", "minerals", "fish", "rivers", "trees", "building_stones", "decorations", "terrains"}
            ),
            "custom_controls_applied": sorted((custom_sections or {}).keys()),
            "custom_object_replacements": list(custom_objects.get("replaced", ())) if custom_objects else [],
            "custom_start_forest": (
                custom_objects.get("start_forest", {})
                if custom_objects else {}
            ),
            "custom_start_bonus_layers": sorted(
                key for key, package in {
                    "forest": "start_forest",
                    "building_stones": "start_building_stones",
                    "mini_swamp": "start_mini_swamp",
                    "rocky_minerals": "start_rocky_minerals",
                    "lake_fish_river": "start_lake_fish_river",
                }.items()
                if package in active_start_packages
            ),
            "note": (
                "Les sections Custom et les bonus de départ activés sont raccordés ; les familles d’objets non modifiées restent natives."
                if custom_sections is not None or active_start_packages
                else "Le cœur Legacy natif conserve sa sortie validée ; aucune section Custom n’est modifiée."
            ),
        }
    return state, validations


__all__ = ("generate",)
