"""Catalogue des archétypes de carte, indépendant des moteurs d'exécution."""

from __future__ import annotations

from dataclasses import dataclass

from .continental import ContinentalContext, ContinentalV1
from .masses import MacroMassReport, analyze_macro_masses, analyze_startable_masses
from .noise_sources import (
    NOISE_SOURCE_SETTING_APPLICABILITY,
    noise_source_setting_applies,
)
from .morphology import (
    NoiseLabReport,
    NoiseLayerDiagnostic,
    apply_archetype_morphology,
    apply_archetype_noise_morphology,
    apply_native_noise_layers,
    apply_native_relief_source,
    build_noise_lab,
    generate_noise_component_previews,
    generate_mask_component_previews,
    generate_shape_template_preview,
    has_active_noise_layers,
    has_active_relief_source,
)
from .previews import (
    MACRO_BEACH,
    MACRO_CLASS_COUNT,
    MACRO_GRASS,
    MACRO_MOUNTAIN,
    MACRO_PALETTE,
    MACRO_SNOW,
    MACRO_WATER,
    ArchetypePreview,
    classify_macro,
    generate_archetype_indicative_preview,
    generate_archetype_noise_preview,
    generate_archetype_preview,
    macro_percentages,
    macro_rgb,
    noise_delta_rgb,
    noise_rgb,
    project_preview_rgb,
    raw_height_rgb,
)
from .profiles import (
    ARCHETYPE_PROFILE_SCHEMA_VERSION,
    CLASSIC_PROFILE_NAME,
    CONTINENTAL_ARCHETYPE_PROFILE,
    CONTINENTAL_CUSTOM_PROFILE_KEY,
    CONTINENTAL_CUSTOM_PROFILE_NAME,
    continental_legacy_blocks_profile,
    continental_noise_calibration_profile,
    CONTINENTAL_PARAMETER_DESCRIPTORS,
    FINITE_DOMAIN_MODE_NATIVE_CALIBRATED,
    FINITE_DOMAIN_MODE_OPTIONS,
    NATIVE_CALIBRATED_FALLOFF_CELLS,
    NATIVE_CALIBRATED_FRAME_CELLS,
    MIN_MOUNTAIN_SNOW_THRESHOLD_GAP,
    MORPHOLOGY_BOUNDS,
    MORPHOLOGY_DEFAULTS,
    NATIVE_NOISE_MAXIMUM,
    NATIVE_NOISE_MINIMUM,
    NOISE_LAYER_COUNT,
    NOISE_LAYER_COUNT_BOUNDS,
    NOISE_LAYER_DEFAULT_COUNT,
    NOISE_LAYER_DEFAULTS,
    NOISE_LAYER_FAMILY_OPTIONS,
    NOISE_LAYER_MASK_OPTIONS,
    NOISE_LAYER_OPERATION_OPTIONS,
    NOISE_LAYER_ORDER_BOUNDS,
    NOISE_LAYER_ROLE_OPTIONS,
    NOISE_LAYER_SCALE_BOUNDS,
    NOISE_LAYER_SOURCE_OPTIONS,
    NOISE_LAYER_STAGE_OPTIONS,
    NOISE_LAYER_STRENGTH_BOUNDS,
    NOISE_MASK_BOUNDS,
    NOISE_MASK_DEFAULTS,
    NOISE_MASK_INCREMENTS,
    NOISE_MASK_SOURCE_OPTIONS,
    NOISE_MASK_TYPE_OPTIONS,
    SHAPE_TEMPLATE_BOUNDS,
    SHAPE_TEMPLATE_DEFAULTS,
    SHAPE_TEMPLATE_INCREMENTS,
    SHAPE_TEMPLATE_TYPE_OPTIONS,
    MASK_LAYER_COUNT,
    MASK_LAYER_COUNT_BOUNDS,
    MASK_LAYER_COMMON_BOUNDS,
    MASK_LAYER_COMMON_DEFAULTS,
    MASK_LAYER_COMMON_INCREMENTS,
    MASK_LAYER_DEFAULT_COUNT,
    MASK_LAYER_DEFAULTS,
    MASK_LAYER_MANUAL_GRID_SIDE,
    MASK_LAYER_OPERATION_OPTIONS,
    MASK_LAYER_ORDER_BOUNDS,
    MASK_LAYER_STRENGTH_BOUNDS,
    MASK_LAYER_TYPE_OPTIONS,
    NOISE_SOURCE_OPTIONS,
    NOISE_SOURCE_SETTING_BOUNDS,
    NOISE_SOURCE_SETTING_DEFAULTS,
    NOISE_SOURCE_SETTING_INCREMENTS,
    RELIEF_SOURCE_DEFAULT,
    RELIEF_SOURCE_CUSTOM_LEGACY,
    RELIEF_SOURCE_LARGE_ISLANDS,
    RELIEF_SOURCE_LARGE_ISLANDS_R21,
    ISLAND_RELIEF_SOURCES,
    CUSTOM_LEGACY_MOUNTAIN_THRESHOLD,
    CUSTOM_LEGACY_SNOW_THRESHOLD,
    thresholds_on_relief_source_change,
    RELIEF_SOURCE_OPTIONS,
    ArchetypeParameterDescriptor,
    archetype_contract_values,
    continental_noise_calibration_profile,
    default_archetype_profile,
    duplicate_noise_layer,
    iter_archetype_parameter_descriptors,
    finite_domain_parameters,
    morphology_parameters,
    noise_layer_parameters,
    mask_layer_parameters,
    has_active_mask_layers,
    normalize_archetype_profile,
    remove_noise_layer,
    reorder_noise_layers,
    duplicate_mask_layer,
    remove_mask_layer,
    reorder_mask_layers,
    relief_source_parameter,
    relief_source_mask,
    relief_source_settings,
    shape_template,
    has_active_shape_template,
    relief_thresholds,
)
from .qualification import (
    ARCHETYPE_TARGETS,
    CONTINENTAL_CALIBRATION_MIRROR_MODES,
    CONTINENTAL_CALIBRATION_PROFILE_NAME,
    CONTINENTAL_CALIBRATION_SEEDS,
    CONTINENTAL_CALIBRATION_SHAPE_SCALE_PERCENT,
    CONTINENTAL_CALIBRATION_RELIEF_CONTRAST_PERCENT,
    CONTINENTAL_CALIBRATION_SIZES,
    MANUAL_MASK_COVERAGE_TOLERANCE_PERCENT,
    MANUAL_MASK_QUALIFICATION_MIRROR_MODES,
    MANUAL_MASK_QUALIFICATION_SEEDS,
    MANUAL_MASK_QUALIFICATION_SIZES,
    QUALIFICATION_DEFAULT_SEED,
    QUALIFICATION_MIRROR_MODES,
    QUALIFICATION_REPRESENTATIVE_SIZES,
    QUALIFICATION_SIZES,
    ArchetypeTargetSpec,
    ContinentalStartQualificationCase,
    ManualMaskQualificationCase,
    ProviderQualification,
    QualificationCheck,
    QualificationMetrics,
    manual_mask_fixture_grid,
    manual_mask_profile,
    manual_mask_report,
    continental_calibration_profile,
    continental_calibration_report,
    continental_custom_report,
    measure_preview,
    qualification_player_cases,
    qualification_report,
    qualify_preview,
    qualify_providers,
    target_matrix,
    target_spec,
)


@dataclass(frozen=True)
class Archetype:
    key: str
    label: str
    implemented: bool
    description: str

ARCHETYPES = {
    'continental': Archetype(
        'continental', 'Continental', True,
        'Macro-topologie : une masse terrestre principale avec océan périphérique.'
    ),
    'large_islands': Archetype(
        'large_islands', 'Large Islands', True,
        'Macro-topologie : plusieurs grandes masses insulaires.'
    ),
    'small_islands': Archetype(
        'small_islands', 'Small Islands', False,
        'Macro-topologie : nombreuses petites masses insulaires.'
    ),
}

ARCHETYPE_ORDER = ('continental', 'large_islands', 'small_islands')

def get_archetype(key: str) -> Archetype:
    try:
        return ARCHETYPES[key]
    except KeyError as exc:
        raise ValueError(f'Archétype inconnu: {key}') from exc


__all__ = [
    "ARCHETYPES",
    "ARCHETYPE_ORDER",
    "ARCHETYPE_PROFILE_SCHEMA_VERSION",
    "ARCHETYPE_TARGETS",
    "CONTINENTAL_CALIBRATION_MIRROR_MODES",
    "CONTINENTAL_CALIBRATION_PROFILE_NAME",
    "CONTINENTAL_CALIBRATION_SEEDS",
    "CONTINENTAL_CALIBRATION_SHAPE_SCALE_PERCENT",
    "CONTINENTAL_CALIBRATION_RELIEF_CONTRAST_PERCENT",
    "CONTINENTAL_CALIBRATION_SIZES",
    "MANUAL_MASK_COVERAGE_TOLERANCE_PERCENT",
    "MANUAL_MASK_QUALIFICATION_MIRROR_MODES",
    "MANUAL_MASK_QUALIFICATION_SEEDS",
    "MANUAL_MASK_QUALIFICATION_SIZES",
    "CONTINENTAL_ARCHETYPE_PROFILE",
    "CONTINENTAL_CUSTOM_PROFILE_KEY",
    "CONTINENTAL_CUSTOM_PROFILE_NAME",
    "CLASSIC_PROFILE_NAME",
    "continental_legacy_blocks_profile",
    "continental_noise_calibration_profile",
    "CONTINENTAL_PARAMETER_DESCRIPTORS",
    "FINITE_DOMAIN_MODE_NATIVE_CALIBRATED",
    "FINITE_DOMAIN_MODE_OPTIONS",
    "MACRO_BEACH",
    "MACRO_CLASS_COUNT",
    "MACRO_GRASS",
    "MACRO_MOUNTAIN",
    "MACRO_PALETTE",
    "MACRO_SNOW",
    "MACRO_WATER",
    "MIN_MOUNTAIN_SNOW_THRESHOLD_GAP",
    "MORPHOLOGY_BOUNDS",
    "MORPHOLOGY_DEFAULTS",
    "NATIVE_NOISE_MAXIMUM",
    "NATIVE_NOISE_MINIMUM",
    "NATIVE_CALIBRATED_FALLOFF_CELLS",
    "NATIVE_CALIBRATED_FRAME_CELLS",
    "NOISE_LAYER_COUNT",
    "NOISE_LAYER_COUNT_BOUNDS",
    "NOISE_LAYER_DEFAULT_COUNT",
    "NOISE_LAYER_DEFAULTS",
    "NOISE_LAYER_FAMILY_OPTIONS",
    "NOISE_LAYER_MASK_OPTIONS",
    "NOISE_LAYER_OPERATION_OPTIONS",
    "NOISE_LAYER_ORDER_BOUNDS",
    "NOISE_LAYER_ROLE_OPTIONS",
    "NOISE_LAYER_SCALE_BOUNDS",
    "NOISE_LAYER_SOURCE_OPTIONS",
    "NOISE_LAYER_STAGE_OPTIONS",
    "NOISE_LAYER_STRENGTH_BOUNDS",
    "NOISE_MASK_BOUNDS",
    "NOISE_MASK_DEFAULTS",
    "NOISE_MASK_INCREMENTS",
    "NOISE_MASK_SOURCE_OPTIONS",
    "NOISE_MASK_TYPE_OPTIONS",
    "MASK_LAYER_COUNT",
    "MASK_LAYER_COUNT_BOUNDS",
    "MASK_LAYER_COMMON_BOUNDS",
    "MASK_LAYER_COMMON_DEFAULTS",
    "MASK_LAYER_COMMON_INCREMENTS",
    "MASK_LAYER_DEFAULT_COUNT",
    "MASK_LAYER_DEFAULTS",
    "MASK_LAYER_MANUAL_GRID_SIDE",
    "MASK_LAYER_OPERATION_OPTIONS",
    "MASK_LAYER_ORDER_BOUNDS",
    "MASK_LAYER_STRENGTH_BOUNDS",
    "MASK_LAYER_TYPE_OPTIONS",
    "SHAPE_TEMPLATE_BOUNDS",
    "SHAPE_TEMPLATE_DEFAULTS",
    "SHAPE_TEMPLATE_INCREMENTS",
    "SHAPE_TEMPLATE_TYPE_OPTIONS",
    "NOISE_SOURCE_OPTIONS",
    "NOISE_SOURCE_SETTING_APPLICABILITY",
    "NOISE_SOURCE_SETTING_BOUNDS",
    "NOISE_SOURCE_SETTING_DEFAULTS",
    "NOISE_SOURCE_SETTING_INCREMENTS",
    "QUALIFICATION_DEFAULT_SEED",
    "QUALIFICATION_MIRROR_MODES",
    "QUALIFICATION_REPRESENTATIVE_SIZES",
    "QUALIFICATION_SIZES",
    "RELIEF_SOURCE_DEFAULT",
    "RELIEF_SOURCE_CUSTOM_LEGACY",
    "RELIEF_SOURCE_LARGE_ISLANDS",
    "RELIEF_SOURCE_LARGE_ISLANDS_R21",
    "ISLAND_RELIEF_SOURCES",
    "CUSTOM_LEGACY_MOUNTAIN_THRESHOLD",
    "CUSTOM_LEGACY_SNOW_THRESHOLD",
    "thresholds_on_relief_source_change",
    "RELIEF_SOURCE_OPTIONS",
    "Archetype",
    "ArchetypeParameterDescriptor",
    "ArchetypePreview",
    "ArchetypeTargetSpec",
    "ContinentalContext",
    "ContinentalV1",
    "ContinentalStartQualificationCase",
    "MacroMassReport",
    "ManualMaskQualificationCase",
    "NoiseLabReport",
    "NoiseLayerDiagnostic",
    "ProviderQualification",
    "QualificationCheck",
    "QualificationMetrics",
    "analyze_macro_masses",
    "analyze_startable_masses",
    "apply_archetype_morphology",
    "apply_archetype_noise_morphology",
    "apply_native_noise_layers",
    "apply_native_relief_source",
    "archetype_contract_values",
    "build_noise_lab",
    "classify_macro",
    "default_archetype_profile",
    "duplicate_noise_layer",
    "generate_archetype_indicative_preview",
    "generate_noise_component_previews",
    "generate_mask_component_previews",
    "generate_shape_template_preview",
    "generate_archetype_noise_preview",
    "generate_archetype_preview",
    "get_archetype",
    "has_active_noise_layers",
    "has_active_relief_source",
    "has_active_shape_template",
    "has_active_mask_layers",
    "iter_archetype_parameter_descriptors",
    "finite_domain_parameters",
    "macro_percentages",
    "macro_rgb",
    "measure_preview",
    "manual_mask_fixture_grid",
    "manual_mask_profile",
    "manual_mask_report",
    "continental_calibration_profile",
    "continental_calibration_report",
    "continental_custom_report",
    "continental_noise_calibration_profile",
    "morphology_parameters",
    "noise_delta_rgb",
    "noise_layer_parameters",
    "mask_layer_parameters",
    "noise_rgb",
    "noise_source_setting_applies",
    "normalize_archetype_profile",
    "remove_noise_layer",
    "reorder_noise_layers",
    "duplicate_mask_layer",
    "remove_mask_layer",
    "reorder_mask_layers",
    "project_preview_rgb",
    "qualification_player_cases",
    "qualification_report",
    "qualify_preview",
    "qualify_providers",
    "raw_height_rgb",
    "relief_source_parameter",
    "relief_source_mask",
    "relief_source_settings",
    "relief_thresholds",
    "shape_template",
    "target_matrix",
    "target_spec",
]
