"""Map, statistics and chart export translation catalogues."""

EXPORT_TEXT={
 'fr':{
  'map_title':'Exporter la carte','stats_title':'Exporter les statistiques et le graphique','folder':'Dossier','browse':'Parcourir…','basename':'Nom de base','formats':'Formats','files':'Fichiers prévus','none':'Sélectionnez au moins un format.','cancel':'Annuler','export':'Exporter','overwrite_title':'Fichiers existants','overwrite':'Ces fichiers existent déjà :\n\n{files}\n\nLes remplacer ?','invalid_name':'Le nom de base est vide ou invalide.','invalid_folder':'Sélectionnez un dossier de sortie valide.','done':'Export terminé :\n\n{files}',
  'edm':'Carte éditeur (.EDM)','map':'Carte jouable (.MAP)','sav':'SAV source inchangé (.SAV)','png_global':'Carte globale, projection active (.PNG)','png_current':'Vue actuelle avec ses couches (.PNG)','json':'Statistiques complètes (.JSON)','csv':'Statistiques complètes (.CSV)','png':'Graphique actuellement affiché (.PNG)',
  'binary_unavailable':'EDM/MAP indisponibles : aucun scaffold validé pour cette taille.','binary_experimental':'Taille hors 768 : export EDM/MAP autorisé pour test ; la viabilité dans l’éditeur/jeu reste à vérifier.','sav_unavailable':'SAV indisponible : seule la copie inchangée d’un SAV importé est autorisée.','sav_exact':'Le SAV sera copié octet pour octet ; aucun writer SAV n’est utilisé.','current_unavailable':'Vue actuelle indisponible : avec Global, elle serait identique au PNG Global.','safe_name':'Les caractères incompatibles avec Windows sont remplacés par « _ ».',
 },
 'en':{
  'map_title':'Export map','stats_title':'Export statistics and chart','folder':'Folder','browse':'Browse…','basename':'Base name','formats':'Formats','files':'Planned files','none':'Select at least one format.','cancel':'Cancel','export':'Export','overwrite_title':'Existing files','overwrite':'These files already exist:\n\n{files}\n\nReplace them?','invalid_name':'The base name is empty or invalid.','invalid_folder':'Select a valid output folder.','done':'Export complete:\n\n{files}',
  'edm':'Editor map (.EDM)','map':'Playable map (.MAP)','sav':'Unchanged source SAV (.SAV)','png_global':'Global map, active projection (.PNG)','png_current':'Current view with its layers (.PNG)','json':'Complete statistics (.JSON)','csv':'Complete statistics (.CSV)','png':'Currently displayed chart (.PNG)',
  'binary_unavailable':'EDM/MAP unavailable: no validated scaffold exists for this size.','binary_experimental':'Outside 768: EDM/MAP export remains enabled for testing; editor/game viability still needs checking.','sav_unavailable':'SAV unavailable: only an unchanged copy of an imported SAV is allowed.','sav_exact':'The SAV is copied byte for byte; no SAV writer is used.','current_unavailable':'Current View unavailable: with Global selected, it would be identical to the Global PNG.','safe_name':'Characters incompatible with Windows are replaced with “_”.',
 },
}

EXPORT_TEXT.update({
 'de':{
  'map_title':'Karte exportieren','stats_title':'Statistiken und Diagramm exportieren','folder':'Ordner','browse':'Durchsuchen…','basename':'Basisname','formats':'Formate','files':'Geplante Dateien','none':'Mindestens ein Format auswählen.','cancel':'Abbrechen','export':'Exportieren','overwrite_title':'Vorhandene Dateien','overwrite':'Diese Dateien sind bereits vorhanden:\n\n{files}\n\nErsetzen?','invalid_name':'Der Basisname ist leer oder ungültig.','invalid_folder':'Einen gültigen Ausgabeordner auswählen.','done':'Export abgeschlossen:\n\n{files}','edm':'Editor-Karte (.EDM)','map':'Spielbare Karte (.MAP)','sav':'Unveränderte Quell-SAV (.SAV)','png_global':'Globale Karte, aktive Projektion (.PNG)','png_current':'Aktuelle Ansicht mit Ebenen (.PNG)','json':'Vollständige Statistiken (.JSON)','csv':'Vollständige Statistiken (.CSV)','png':'Aktuell angezeigtes Diagramm (.PNG)','binary_unavailable':'EDM/MAP nicht verfügbar: kein validiertes Scaffold für diese Größe.','binary_experimental':'Außerhalb von 768: EDM/MAP-Export bleibt zum Testen aktiviert; Editor-/Spieltauglichkeit muss noch geprüft werden.','sav_unavailable':'SAV nicht verfügbar: nur eine unveränderte Kopie einer importierten SAV ist erlaubt.','sav_exact':'Die SAV wird Byte für Byte kopiert; es wird kein SAV-Writer verwendet.','current_unavailable':'Aktuelle Ansicht nicht verfügbar: mit Global wäre sie identisch mit dem globalen PNG.','safe_name':'Mit Windows inkompatible Zeichen werden durch „_“ ersetzt.',
 },
 'es':{
  'map_title':'Exportar mapa','stats_title':'Exportar estadísticas y gráfico','folder':'Carpeta','browse':'Examinar…','basename':'Nombre base','formats':'Formatos','files':'Archivos previstos','none':'Selecciona al menos un formato.','cancel':'Cancelar','export':'Exportar','overwrite_title':'Archivos existentes','overwrite':'Estos archivos ya existen:\n\n{files}\n\n¿Reemplazarlos?','invalid_name':'El nombre base está vacío o no es válido.','invalid_folder':'Selecciona una carpeta de salida válida.','done':'Exportación terminada:\n\n{files}','edm':'Mapa del editor (.EDM)','map':'Mapa jugable (.MAP)','sav':'SAV de origen sin cambios (.SAV)','png_global':'Mapa global, proyección activa (.PNG)','png_current':'Vista actual con sus capas (.PNG)','json':'Estadísticas completas (.JSON)','csv':'Estadísticas completas (.CSV)','png':'Gráfico mostrado actualmente (.PNG)','binary_unavailable':'EDM/MAP no disponibles: no existe un scaffold validado para este tamaño.','binary_experimental':'Fuera de 768: el export EDM/MAP sigue habilitado para pruebas; aún hay que comprobar la viabilidad en el editor/juego.','sav_unavailable':'SAV no disponible: solo se permite una copia sin cambios de un SAV importado.','sav_exact':'El SAV se copia byte por byte; no se utiliza ningún writer SAV.','current_unavailable':'Vista actual no disponible: con Global sería idéntica al PNG Global.','safe_name':'Los caracteres incompatibles con Windows se sustituyen por «_».',
 },
})
