"""History, comparison and capacity-dialog translation catalogues."""

HISTORY_TEXT={
 'fr':{'title':'Centre d’historique','origin':'Origine','map':'Carte','details':'Détails','preview':'Aperçu sélectionné','generated':'Génération','batch':'Lot','imported':'Import','show':'Afficher','set_a':'Affecter à A','set_b':'Affecter à B','delete':'Supprimer','clear':'Tout vider','close':'Fermer','empty':'Aucune carte dans cette session.','none':'Aucun','current':'Carte actuellement affichée','comparison':'Slot de comparaison : {slots}','mru':'Position MRU : {position}/{total}','source':'Source : {path}','protected':'Protégée : {reasons}','main_view':'vue principale','outside_history':'Carte affichée hors historique','confirm_clear':'Vider entièrement l’historique de session ?','confirm_clear_protected':'Des cartes sont protégées par : {reasons}. Les slots A/B seront libérés et la carte affichée restera visible hors historique. Continuer ?','delete_assigned':'Cette carte est protégée par : {reasons}. Sa suppression libérera ses slots A/B et, si elle est affichée, la laissera visible hors historique. Continuer ?','deleted':'Entrée supprimée de l’historique.','capacity':'{used} / {count} cartes · mémoire de session uniquement','capacity_reduce':'Réduire la capacité de {old} à {new} supprimera {removed} carte(s) ancienne(s) non protégée(s). Continuer ?'},
 'en':{'title':'History Center','origin':'Origin','map':'Map','details':'Details','preview':'Selected preview','generated':'Generated','batch':'Batch','imported':'Import','show':'Show','set_a':'Assign to A','set_b':'Assign to B','delete':'Delete','clear':'Clear all','close':'Close','empty':'No map in this session.','none':'None','current':'Currently displayed map','comparison':'Comparison slot: {slots}','mru':'MRU position: {position}/{total}','source':'Source: {path}','protected':'Protected: {reasons}','main_view':'main viewer','outside_history':'Displayed map outside history','confirm_clear':'Clear the entire session history?','confirm_clear_protected':'Maps are protected by: {reasons}. A/B slots will be cleared and the displayed map will remain visible outside history. Continue?','delete_assigned':'This map is protected by: {reasons}. Deleting it will clear its A/B slots and, if displayed, leave it visible outside history. Continue?','deleted':'History entry deleted.','capacity':'{used} / {count} maps · session memory only','capacity_reduce':'Reducing capacity from {old} to {new} will remove {removed} older unprotected map(s). Continue?'},
 'de':{'title':'Verlaufszentrum','origin':'Quelle','map':'Karte','details':'Details','preview':'Ausgewählte Vorschau','generated':'Generiert','batch':'Stapel','imported':'Import','show':'Anzeigen','set_a':'A zuweisen','set_b':'B zuweisen','delete':'Löschen','clear':'Alles leeren','close':'Schließen','empty':'Keine Karte in dieser Sitzung.','none':'Keine','current':'Aktuell angezeigte Karte','comparison':'Vergleichsplatz: {slots}','mru':'MRU-Position: {position}/{total}','source':'Quelle: {path}','protected':'Geschützt: {reasons}','main_view':'Hauptansicht','outside_history':'Angezeigte Karte außerhalb des Verlaufs','confirm_clear':'Den gesamten Sitzungsverlauf leeren?','confirm_clear_protected':'Karten sind geschützt durch: {reasons}. A/B werden freigegeben; die angezeigte Karte bleibt außerhalb des Verlaufs sichtbar. Fortfahren?','delete_assigned':'Diese Karte ist geschützt durch: {reasons}. Beim Löschen werden A/B freigegeben; eine angezeigte Karte bleibt außerhalb des Verlaufs sichtbar. Fortfahren?','deleted':'Verlaufseintrag gelöscht.','capacity':'{used} / {count} Karten · nur Sitzungsspeicher','capacity_reduce':'Die Verringerung von {old} auf {new} entfernt {removed} ältere ungeschützte Karte(n). Fortfahren?'},
 'es':{'title':'Centro de historial','origin':'Origen','map':'Mapa','details':'Detalles','preview':'Vista previa seleccionada','generated':'Generación','batch':'Lote','imported':'Importación','show':'Mostrar','set_a':'Asignar a A','set_b':'Asignar a B','delete':'Eliminar','clear':'Vaciar todo','close':'Cerrar','empty':'No hay mapas en esta sesión.','none':'Ninguno','current':'Mapa mostrado actualmente','comparison':'Ranura de comparación: {slots}','mru':'Posición MRU: {position}/{total}','source':'Origen: {path}','protected':'Protegido: {reasons}','main_view':'visor principal','outside_history':'Mapa mostrado fuera del historial','confirm_clear':'¿Vaciar todo el historial de sesión?','confirm_clear_protected':'Hay mapas protegidos por: {reasons}. Se vaciarán A/B y el mapa mostrado seguirá visible fuera del historial. ¿Continuar?','delete_assigned':'Este mapa está protegido por: {reasons}. Al eliminarlo se vaciarán sus ranuras A/B y, si está mostrado, seguirá visible fuera del historial. ¿Continuar?','deleted':'Entrada eliminada del historial.','capacity':'{used} / {count} mapas · solo memoria de sesión','capacity_reduce':'Reducir la capacidad de {old} a {new} eliminará {removed} mapa(s) antiguo(s) no protegido(s). ¿Continuar?'},
}

_HISTORY_MANUAL_TEXT={
 'fr':{'lock':'Verrouiller','unlock':'Déverrouiller','move_up':'Monter','move_down':'Descendre','display_position':'Position affichée : {position}/{total}','manual_lock':'verrouillage manuel','locked':'Carte verrouillée manuellement dans le cache.','unlocked':'Verrouillage manuel retiré.','capacity_protected':'La capacité {new} est inférieure aux {protected} cartes actuellement protégées. Libérez d’abord des slots ou des verrouillages manuels.','confirm_clear_protected':'Des cartes sont protégées par : {reasons}. Les slots A/B et les verrouillages manuels seront libérés ; la carte affichée restera visible hors historique. Continuer ?','delete_assigned':'Cette carte est protégée par : {reasons}. Sa suppression libérera ses slots A/B et son verrouillage manuel ; si elle est affichée, elle restera visible hors historique. Continuer ?'},
 'en':{'lock':'Lock','unlock':'Unlock','move_up':'Move up','move_down':'Move down','display_position':'Displayed position: {position}/{total}','manual_lock':'manual lock','locked':'Map manually locked in the cache.','unlocked':'Manual lock removed.','capacity_protected':'Capacity {new} is lower than the {protected} currently protected maps. Clear slots or manual locks first.','confirm_clear_protected':'Maps are protected by: {reasons}. A/B slots and manual locks will be cleared; the displayed map will remain visible outside history. Continue?','delete_assigned':'This map is protected by: {reasons}. Deleting it will clear its A/B slots and manual lock; if displayed, it will remain visible outside history. Continue?'},
 'de':{'lock':'Sperren','unlock':'Entsperren','move_up':'Nach oben','move_down':'Nach unten','display_position':'Anzeigeposition: {position}/{total}','manual_lock':'manuelle Sperre','locked':'Karte manuell im Cache gesperrt.','unlocked':'Manuelle Sperre entfernt.','capacity_protected':'Die Kapazität {new} ist kleiner als die {protected} derzeit geschützten Karten. Geben Sie zuerst Plätze oder manuelle Sperren frei.','confirm_clear_protected':'Karten sind geschützt durch: {reasons}. A/B und manuelle Sperren werden freigegeben; die angezeigte Karte bleibt außerhalb des Verlaufs sichtbar. Fortfahren?','delete_assigned':'Diese Karte ist geschützt durch: {reasons}. Beim Löschen werden A/B und die manuelle Sperre freigegeben; eine angezeigte Karte bleibt außerhalb des Verlaufs. Fortfahren?'},
 'es':{'lock':'Bloquear','unlock':'Desbloquear','move_up':'Subir','move_down':'Bajar','display_position':'Posición mostrada: {position}/{total}','manual_lock':'bloqueo manual','locked':'Mapa bloqueado manualmente en la caché.','unlocked':'Bloqueo manual eliminado.','capacity_protected':'La capacidad {new} es inferior a los {protected} mapas protegidos actualmente. Libera primero ranuras o bloqueos manuales.','confirm_clear_protected':'Hay mapas protegidos por: {reasons}. Se vaciarán A/B y los bloqueos manuales; el mapa mostrado seguirá visible fuera del historial. ¿Continuar?','delete_assigned':'Este mapa está protegido por: {reasons}. Al eliminarlo se vaciarán A/B y su bloqueo manual; si está mostrado, seguirá visible fuera del historial. ¿Continuar?'},
}

for _lang,_values in _HISTORY_MANUAL_TEXT.items():HISTORY_TEXT[_lang].update(_values)

_CONTEXT_TEXT={
 'fr':{'loaded':'Chargée !','shown':'Affichée !','assigned_a':'Affectée à A !','assigned_b':'Affectée à B !','lock_tip':'Protection : {roles}','viewer_role':'V = vue principale (une génération simple déplace V vers son nouveau résultat)','manual_role':'M = verrouillage manuel','outside_tip':'Cette carte reste affichée, mais elle ne se trouve plus dans le cache de session.'},
 'en':{'loaded':'Loaded!','shown':'Shown!','assigned_a':'Assigned to A!','assigned_b':'Assigned to B!','lock_tip':'Protection: {roles}','viewer_role':'V = main viewer (simple generation moves V to its new result)','manual_role':'M = manual lock','outside_tip':'This map is still displayed, but is no longer in the session cache.'},
 'de':{'loaded':'Geladen!','shown':'Angezeigt!','assigned_a':'A zugewiesen!','assigned_b':'B zugewiesen!','lock_tip':'Schutz: {roles}','viewer_role':'V = Hauptansicht (eine einfache Generierung verschiebt V zum neuen Ergebnis)','manual_role':'M = manuelle Sperre','outside_tip':'Diese Karte wird noch angezeigt, befindet sich aber nicht mehr im Sitzungscache.'},
 'es':{'loaded':'¡Cargado!','shown':'¡Mostrado!','assigned_a':'¡Asignado a A!','assigned_b':'¡Asignado a B!','lock_tip':'Protección: {roles}','viewer_role':'V = visor principal (una generación simple mueve V al nuevo resultado)','manual_role':'M = bloqueo manual','outside_tip':'Este mapa sigue mostrándose, pero ya no está en la caché de sesión.'},
}

_HISTORY_CAPACITY_DIALOG_TEXT={
 'fr':{'title':'Réduire la capacité de l’historique','continue':'Réduire','cancel':'Annuler'},
 'en':{'title':'Reduce history capacity','continue':'Reduce','cancel':'Cancel'},
 'de':{'title':'Verlaufskapazität verringern','continue':'Verringern','cancel':'Abbrechen'},
 'es':{'title':'Reducir la capacidad del historial','continue':'Reducir','cancel':'Cancelar'},
}
